In [1]:
import pandas as pd

In [10]:
df=pd.read_csv('spotify_tracks.csv')
df

,id,name,genre,artists,album,popularity,duration_ms,explicit
0,7kr3xZk4yb3YSZ4VFtg2Qt,Acoustic,acoustic,Billy Raffoul,1975,58,172199,False
1,1kJygfS4eoVziBBI93MSYp,Acoustic,acoustic,Billy Raffoul,A Few More Hours at YYZ,57,172202,False
2,6lynns69p4zTCRxmmiSY1x,Here Comes the Sun - Acoustic,acoustic,"Molly Hocking, Bailey Rushlow",Here Comes the Sun (Acoustic),42,144786,False
3,1RC9slv335IfLce5vt9KTW,Acoustic #3,acoustic,The Goo Goo Dolls,Dizzy up the Girl,46,116573,False
4,5o9L8xBuILoVjLECSBi7Vo,My Love Mine All Mine - Acoustic Instrumental,acoustic,"Guus Dielissen, Casper Esmann",My Love Mine All Mine (Acoustic Instrumental),33,133922,False
...,...,...,...,...,...,...,...,...
6295,4uveHSzaz8YEbTF9j6QlCI,Voyage to Atlantis,world-music,Future World Music,Reign of Vengeance,25,180001,False
6296,4u15cjyziW2Ewn5Ek3082l,L'Oiseau,world-music,"Putumayo, Marianne Perrudin, Thomas Artaud",Global Relaxation by Putumayo,25,276776,False
6297,56pHPaTeX2O9aVmTFYS8hV,The Daintree,world-music,Joseph Tawadros,World Music,12,69533,False
6298,6Ldyc5TsR4kaUsuHKcB2AD,The Sorcerers Symphony,world-music,Future World Music,Behold,26,90001,False
6299,3ry0f8ybk8upUBIk8unvmF,Fiore d'inverno,world-music,"Putumayo, Giacomo Lariccia",World Party 5 by Putumayo,25,141800,False

In [11]:
df.head()

,id,name,genre,artists,album,popularity,duration_ms,explicit
0,7kr3xZk4yb3YSZ4VFtg2Qt,Acoustic,acoustic,Billy Raffoul,1975,58,172199,False
1,1kJygfS4eoVziBBI93MSYp,Acoustic,acoustic,Billy Raffoul,A Few More Hours at YYZ,57,172202,False
2,6lynns69p4zTCRxmmiSY1x,Here Comes the Sun - Acoustic,acoustic,"Molly Hocking, Bailey Rushlow",Here Comes the Sun (Acoustic),42,144786,False
3,1RC9slv335IfLce5vt9KTW,Acoustic #3,acoustic,The Goo Goo Dolls,Dizzy up the Girl,46,116573,False
4,5o9L8xBuILoVjLECSBi7Vo,My Love Mine All Mine - Acoustic Instrumental,acoustic,"Guus Dielissen, Casper Esmann",My Love Mine All Mine (Acoustic Instrumental),33,133922,False

In [12]:
df.columns

Index(['id', 'name', 'genre', 'artists', 'album', 'popularity', 'duration_ms',
       'explicit'],
      dtype='object')

In [14]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6300 entries, 0 to 6299
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           6300 non-null   object
 1   name         6300 non-null   object
 2   genre        6300 non-null   object
 3   artists      6300 non-null   object
 4   album        6300 non-null   object
 5   popularity   6300 non-null   int64
 6   duration_ms  6300 non-null   int64
 7   explicit     6300 non-null   bool
dtypes: bool(1), int64(2), object(5)
memory usage: 350.8+ KB

        popularity   duration_ms
count  6300.000000  6.300000e+03
mean     30.754762  2.028477e+05
std      19.948991  1.210299e+05
min       0.000000  3.006000e+04
25%      16.000000  1.476870e+05
50%      29.000000  1.916070e+05
75%      45.000000  2.369625e+05
max      90.000000  3.601658e+06

In [17]:
#Clean the data(basic)
df.isnull().sum()
df.drop_duplicates(inplace=True)

In [19]:
#ANALYSIS TASKS
#Top 10 most popular songs
top_songs = df.sort_values(by='popularity', ascending=False)[['name', 'artists', 'popularity']].head(10)
print(top_songs)

                                                name  \
1567                                         Houdini
5540         Clean Baby Sleep White Noise (Loopable)
4746                      BAND4BAND (feat. Lil Baby)
3158  One Of The Girls (with JENNIE, Lily Rose Depp)
2797                                       As It Was
3213                                        Magnetic
4745                                Beautiful Things
3356                                        Magnetic
4748                                    Slow It Down
4610                                      Pink Skies

                                                artists  popularity
1567                                             Eminem          90
5540  Dream Supplier, Baby Sleeps, Background White ...          88
4746                              Central Cee, Lil Baby          87
3158                 The Weeknd, JENNIE, Lily-Rose Depp          87
2797                                       Harry Styles          87
3213                                              ILLIT          86
4745                                       Benson Boone          86
3356                                              ILLIT          86
4748                                       Benson Boone          85
4610                                         Zach Bryan          85

In [20]:
#Top 5 most popular artist
top_artists = df.groupby('name')['popularity'].mean().sort_values(ascending=False).head(5)
print(top_artists)

name
Houdini                                           90.0
Clean Baby Sleep White Noise (Loopable)           88.0
One Of The Girls (with JENNIE, Lily Rose Depp)    87.0
As It Was                                         87.0
BAND4BAND (feat. Lil Baby)                        87.0
Name: popularity, dtype: float64

In [24]:
#Average popularity by genre
genre_popularity = df.groupby('genre')['popularity'].mean().sort_values(ascending=False).head(10)
print(genre_popularity)

genre
rock           60.34
dance          57.52
pop            57.32
summer         57.06
country        56.50
party          54.22
sleep          53.64
rock-n-roll    53.54
happy          52.82
soul           52.54
Name: popularity, dtype: float64

In [25]:
#Explicit vs Non-Explicit songs count
df['explicit'].value_counts()

explicit
False    5106
True     1194
Name: count, dtype: int64

In [27]:
#Convert duration into minutes
df['duration_min'] = df['duration_ms'] / 60000
df[['name', 'duration_min']].head()

                                            name  duration_min
0                                       Acoustic      2.869983
1                                       Acoustic      2.870033
2                  Here Comes the Sun - Acoustic      2.413100
3                                    Acoustic #3      1.942883
4  My Love Mine All Mine - Acoustic Instrumental      2.232033

In [28]:
#To get the longest songs
df[['name', 'artists', 'duration_min']].sort_values(by='duration_min', ascending=False).head(10)

,name,artists,duration_min
50,Afrobeat 2023 Mixtape,Dj funkybee,60.027633
1690,Electronic,Mind Amend,60.000233
3039,Industrial Fan (1 Hour White Noise),SleepTherapy,59.916667
60,Afrobeats Mix Flight OSO 149,Osocity,39.540233
4898,Reggaeton 2024 Mix,Osocity,31.228633
2623,The State of Hip hop,"Christopher V green, SLEESTACKZ",25.303350
1658,Electronic,Mind Amend,25.000067
5536,Sleep,Godspeed You! Black Emperor,23.295767
3453,"Latintrap, Vol. 2",Ernesto Bianchi,22.268067
5661,Helpless Child,Swans,15.794433